spring:
  application:
    name: digital-banking
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  base-url: http://localhost:8080
server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html # Path to access the UI in browser
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    url: /v3/api-docs
  packages-to-scan: com.nabgha.digitalbanking.controllers

